# version: '3.9'

services:
  app:
    container_name: cinemag_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      PHP_IDE_CONFIG: "serverName=movie-catalog"
    networks:
      - movie-net

  nginx:
    container_name: cinemag_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - movie-net

  mysql:
    container_name: cinemag_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: movie_catalog
      MYSQL_USER: nette
      MYSQL_PASSWORD: nette
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - movie-net

  redis:
    container_name: cinemag_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - movie-net

  elasticsearch:
    container_name: cinemag_es
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - movie-net

volumes:
  mysql_data:
  es_data:

networks:
  movie-net:
    driver: bridge
